# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindloop < Formula
  desc "Mindloop is a comprehensive productivity suite designed for local-first workflow management."
  homepage "https://github.com/snehmatic/mindloop"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.10.0/mindloop_Darwin_x86_64.tar.gz"
      sha256 "b82c0eabe8b472103dbeaaf191629512283290c0cde5ad705c1af21d147958f4"

      define_method(:install) do
        bin.install "mindloop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.10.0/mindloop_Darwin_arm64.tar.gz"
      sha256 "932d3f715268539b5326d57dc036565ab792eb2af00fccefd1c7f2e009be8397"

      define_method(:install) do
        bin.install "mindloop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.10.0/mindloop_Linux_x86_64.tar.gz"
      sha256 "7455e1f0f93f68d95bad004641bfd5eefa4b687dfb79da5172a7aa6513ebc91f"
      define_method(:install) do
        bin.install "mindloop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.10.0/mindloop_Linux_arm64.tar.gz"
      sha256 "dc2c34b0352f5395ea263d0d85a86fa05d620eae0797c6773e44240a19835b8b"
      define_method(:install) do
        bin.install "mindloop"
      end
    end
  end

  service do
    run [opt_bin/"mindloop", "server"]
    keep_alive true
    log_path var/"log/mindloop.log"
    error_log_path var/"log/mindloop.log"
  end

  test do
    system "#{bin}/mindloop --version"
  end
end
