# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindloop < Formula
  desc "Mindloop is a comprehensive productivity suite designed for local-first workflow management."
  homepage "https://github.com/snehmatic/mindloop"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.7.1/mindloop_Darwin_x86_64.tar.gz"
      sha256 "9a2f3214b27f649a915eb18a11ad6da64df5a41f5cd4186294eee544794acf10"

      define_method(:install) do
        bin.install "mindloop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.7.1/mindloop_Darwin_arm64.tar.gz"
      sha256 "d24bb3b7878c6ac1e113edf3d72d8cd110733915219bd689c5f0d6f5735d8745"

      define_method(:install) do
        bin.install "mindloop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.7.1/mindloop_Linux_x86_64.tar.gz"
      sha256 "af125f52e0a5be2eba45c0ed3b7abce03ccd4a9087ed7f5ee7e8504e74c88f21"
      define_method(:install) do
        bin.install "mindloop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.7.1/mindloop_Linux_arm64.tar.gz"
      sha256 "ab8c6130a25aa0231be4402999504ef6fddd85dddf5001a0b6d47286ba6df389"
      define_method(:install) do
        bin.install "mindloop"
      end
    end
  end

  service do
    run [opt_bin/"mindloop", "server"]
    keep_alive true
    log_path var/"log/mindloop.log"
    error_log_path var/"log/mindloop.log"
  end

  test do
    system "#{bin}/mindloop --version"
  end
end
