# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindloop < Formula
  desc "Mindloop is a comprehensive productivity suite designed for local-first workflow management."
  homepage "https://github.com/snehmatic/mindloop"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.4.1/mindloop_Darwin_x86_64.tar.gz"
      sha256 "f49b13cdefd4c95a6d8954835d577b015292c6824e0f993e6218d4289b614a71"

      def install
        bin.install "mindloop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.4.1/mindloop_Darwin_arm64.tar.gz"
      sha256 "6ddd3416b356ef23cdc2f2ab5bfb18fccc37374664d85f3d64180ca25ccdc80c"

      def install
        bin.install "mindloop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.4.1/mindloop_Linux_x86_64.tar.gz"
      sha256 "6a8f4f9234c6ef0ccf165f07731cfae27a1a7f2e8e747fa012b96c771bf36320"
      def install
        bin.install "mindloop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/snehmatic/mindloop/releases/download/v1.4.1/mindloop_Linux_arm64.tar.gz"
      sha256 "ece1098899a0d9d83066de62b1d3616d42012cbc1192034cf9e7cfd6ee4a481a"
      def install
        bin.install "mindloop"
      end
    end
  end

  service do
    run [opt_bin/"mindloop", "server"]
    keep_alive true
    log_path var/"log/mindloop.log"
    error_log_path var/"log/mindloop.log"
  end

  test do
    system "#{bin}/mindloop --version"
  end
end
